name: Proxmox
run-name: Proxmox Build
on: [push]
jobs:
  Packer:
    name: Run Packer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packer
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.PROXMOX_VE_SSH_PRIVATE_KEY }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Packer init
        run: packer init ./k8_node.pkr.hcl

      - name: Run Packer Validate
        run: packer validate ./k8_node.pkr.hcl

      - name: Build Artifact
        run: packer build \
         -var "ssh_username=${{ secrets.PROXMOX_SSH_USERNAME }}" \
         -var "ssh_password=${{ secrets.PROXMOX_SSH_PASSWORD }}" \
         -var "proxmox_url=${{ secrets.PROXMOX_URL }}" \
         ./k8_node.pkr.hcl

  Terraform:
    needs: Packer
    name: Run Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    env:
      TF_VAR_r2_access_key: ${{ secrets.R2_ACCESS_KEY }}
      TF_VAR_r2_secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      PROXMOX_VE_SSH_PRIVATE_KEY: ${{ secrets.PROXMOX_VE_SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -backend-config="access_key=$TF_VAR_r2_access_key" -backend-config="secret_key=$TF_VAR_r2_secret_access_key"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out tfplan

      - name: Terraform Apply (Main Branch Only)
        if: github.ref_name == 'main'
        run: terraform apply -auto-approve tfplan
