name: Proxmox
run-name: Terraform Build
on: [push]
jobs:
  Terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_r2_access_key: ${{ secrets.R2_ACCESS_KEY }}
      TF_VAR_r2_secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      PROXMOX_VE_SSH_PRIVATE_KEY: ${{ secrets.PROXMOX_VE_SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -backend-config="access_key=$TF_VAR_r2_access_key" -backend-config="secret_key=$TF_VAR_r2_secret_access_key"

      - name: Terraform Plan
        run: terraform plan -out tfplan

      - name: Terraform Apply (Main Branch Only)
        if: github.ref_name == 'main'
        run: terraform apply -auto-approve tfplan
